apiVersion: v1
kind: Secret
metadata:
  name: infra-live-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    avp.kubernetes.io/path: "internal/git/devops"
stringData:
  url: https://git.unity.finance/dev/infra-live.git
  password: <password>
  username: <username>
