apiVersion: v1
kind: Secret
metadata:
  name: infra-live-repo
  namespace: infra-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    avp.kubernetes.io/path: "internal/data/git/devops"
stringData:
  url: <path:internal/data/git/devops#url>
  password: <path:internal/data/git/devops#password>
  username: <path:internal/data/git/devops#username>
